name: Nix Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v10
        with:
          name: maybevoid
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build

      - run: nix run
